### ISSUE TITLE
New Cafe wax event missing

### ISSUE THREAD

**Issue by SympathyTea** [cmstead/sky-clock#15]
I'm unsure of the state of this project but a new timed wax event has been added and wanted to make the maintainers of this project aware of its existence so it can be added.

If more information is needed let me know and I will answer to the best of my ability.

Here are the (updated) theorized times courtesy of discord user LPS100: 
These just got updated when i was writing this, whoops

15 mins long event that occurs every hour, at the start of the hour.
---  
x:00 - Event Start
x:15 - Break
---
It's theorized to have two extra halves in case you missed the first one.
x:30 - Start
x:45 - Break
x:60 - Start
x:05 - Event End
---

**Comment by LPS100** [comment]
Howdy! Here with the updated information - after a lot of research and check-ins, I can conclude that the Cinnamoroll Cafe Bun Event is an **hourly event** that occurs at **xx:00** and ends at **xx:15**. It works similar to Granny, you burn the cupcakes that come in waves and it gives wax - the best way to tell when it's about to happen is when Cinnamoroll is seen holding a tray of cupcakes. During the event, Tip-Toeing Tea Brewer will be annoyed at the oven and exhausted, while Cinnamoroll will be bouncng on the bar table, alerted by the oven. Once the event ends, Tea Brewer will be exhausted and rest on the chair - after 15 mins, she will return to her usual idle animation of greeting the guests and interact with Cinnamoroll.
It's currently unknown if the new wax spot is here to stay, or if it's Cinnamoroll-exclusive.

**Comment by cmstead** [comment]
Thanks for the info! I'd been dragging my feet for a while, but I'm going to try to get this folded in since I assume the wax event will probably stay.

**Comment by nodeMD** [comment]
I have a small PR which adds the event: https://github.com/cmstead/sky-clock/pull/16
@cmstead please review when you will have time 🙇🏻

**Comment by cmstead** [comment]
The cinnamon roll even is gone, so I'm closing. :-(
