### ISSUE TITLE
Sky Shards link

### ISSUE THREAD

**Issue by mspalo** [cmstead/sky-clock#18]
Hi Chris, 
based on our email communication, I am rewriting here the request on adding link on very similar Sky-Shards project:
https://sky-shards.pages.dev/
I will also ask Other project to make link more visible. (maybe based on your decision how will it be look like)

Thank you and have a nice day!
palo

**Comment by cmstead** [comment]
It took me a long time to get around to it, but I added it at the bottom of the calendar so it's easy to find and click.
