### ISSUE TITLE
The contributor section on mobile not properly spaced

### ISSUE THREAD

**Issue by Nafiz1** [cmstead/sky-clock#8]
On mobile the contributor section isn't centered correctly and looks off.

**Comment by nodeMD** [comment]
I made a proposal how to adjust that: https://github.com/cmstead/sky-clock/pull/17
@cmstead please review when you will have time 🙇🏻

**Comment by nodeMD** [comment]
@cmstead I think this one can be closed now 🙂

**Comment by cmstead** [comment]
@nodeMD Thank you for PR!
